### ISSUE TITLE
Expose tensorboard as a route

### ISSUE THREAD

**Issue by maulikjs** [AICoE/jupyterhub-ocp-oauth#36]
So, while trying to run tensorflow, I had to expose tensorboard.
I was able to achieve that by adding a label to my jupyterhub pod, creating a service to use that label as a selector and then exposing the route.

It would be nice to have that as a default whenever I use the tensorflow image to spin up jupyterhub.

As proposed, the easier thing to do would be to add the tensorboard jupyter extension to the base image.

**Comment by vpavlin** [comment]
Here you go https://github.com/vpavlin/jupyter-notebooks/pull/12
